### ISSUE TITLE
[Error] ProcessExitError: Broker server at socket path /tmp/socketcluster/6c3a7eb8-f58e_aa294f3dda/b0

### ISSUE THREAD

**Issue by asterissco** [TopCloud/sc-redis#14]
Hi!!

I follow your instructions and result this error when start node

   [Busy] Launching SocketCluster
   !! The sc-hot-reboot plugin is watching for code changes in the /prueba/test directory
1543502155503 - Origin: BrokerEngine (PID 24521)
   [Error] ProcessExitError: Broker server at socket path /tmp/socketcluster/6c3a7eb8-f58e_aa294f3dda/b0 exited with code 0
    at Server.<anonymous> (/prueba/test/node_modules/sc-broker-cluster/index.js:373:19)
    at Server.emit (events.js:182:13)
    at ChildProcess.<anonymous> (/prueba/test/node_modules/sc-broker/index.js:129:10)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
1543502155587 - Origin: BrokerEngine (PID 24521)

I dont know Why!

**Comment by seiyria** [comment]
I got this error when I didn't supply a valid host/port.
